[build]
  command = "npm run build" # o con yarn: "yarn build".
  functions = "functions" # este comando creará una carpeta llamada "functions" y guardara las funciones Lambda.
  publish = "src" # carpeta que contiene los archivos del proyecto. 

[[redirects]]
  from = "/graphql"
  to = "./netlify/functions/graphql"
  status = 200
  force = true